/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'student' : IDL.Null,
  'driver' : IDL.Null,
  'parent' : IDL.Null,
});
export const Time = IDL.Int;
export const Alert = IDL.Record({
  'id' : IDL.Text,
  'tripId' : IDL.Opt(IDL.Text),
  'routeId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Time,
  'vehicleId' : IDL.Opt(IDL.Text),
});
export const PickupDropoffRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'stopId' : IDL.Text,
  'studentId' : IDL.Principal,
  'tripId' : IDL.Text,
  'time' : Time,
  'notes' : IDL.Opt(IDL.Text),
});
export const Route = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'stops' : IDL.Vec(IDL.Text),
});
export const TripStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'delayed' : IDL.Null,
  'arrived' : IDL.Null,
  'completed' : IDL.Null,
  'enRoute' : IDL.Null,
});
export const Trip = IDL.Record({
  'id' : IDL.Text,
  'status' : TripStatus,
  'lastUpdated' : Time,
  'routeId' : IDL.Text,
  'vehicleId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'assignedRoute' : IDL.Opt(IDL.Text),
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'assignedVehicle' : IDL.Opt(IDL.Text),
});
export const VehicleLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'assignedRoute' : IDL.Opt(IDL.Text),
  'lastUpdated' : Time,
  'longitude' : IDL.Float64,
  'driver' : IDL.Principal,
  'vehicleId' : IDL.Text,
});
export const TripLifecycleAction = IDL.Record({
  'action' : IDL.Text,
  'routeName' : IDL.Text,
  'routeId' : IDL.Text,
  'timestamp' : Time,
  'driver' : IDL.Principal,
  'vehicleId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignDriverVehicleAndRoute' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlert' : IDL.Func([Alert], [], []),
  'createPickupDropoffRecord' : IDL.Func([PickupDropoffRecord], [], []),
  'createRoute' : IDL.Func([Route], [], []),
  'createTrip' : IDL.Func([Trip], [], []),
  'deactivateRoute' : IDL.Func([IDL.Text], [], []),
  'endTripExplicit' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getActiveRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
  'getActiveTripsForDriver' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Trip)],
      ['query'],
    ),
  'getAlert' : IDL.Func([IDL.Text], [IDL.Opt(Alert)], ['query']),
  'getAlertsForRoute' : IDL.Func([IDL.Text], [IDL.Vec(Alert)], ['query']),
  'getAlertsForVehicle' : IDL.Func([IDL.Text], [IDL.Vec(Alert)], ['query']),
  'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllPickupDropoffRecords' : IDL.Func(
      [],
      [IDL.Vec(PickupDropoffRecord)],
      ['query'],
    ),
  'getAllRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllVehicleLocations' : IDL.Func(
      [],
      [IDL.Vec(VehicleLocation)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDriverTripHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TripLifecycleAction)],
      ['query'],
    ),
  'getPickupDropoffRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PickupDropoffRecord)],
      ['query'],
    ),
  'getPickupDropoffRecordsForStudent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PickupDropoffRecord)],
      ['query'],
    ),
  'getRoute' : IDL.Func([IDL.Text], [IDL.Opt(Route)], ['query']),
  'getTrip' : IDL.Func([IDL.Text], [IDL.Opt(Trip)], ['query']),
  'getTripsForVehicle' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicleLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VehicleLocation)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'startTripExplicit' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePickupDropoffRecord' : IDL.Func([PickupDropoffRecord], [], []),
  'updateRoute' : IDL.Func([Route], [], []),
  'updateTripStatus' : IDL.Func([IDL.Text, TripStatus], [], []),
  'updateVehicleLocation' : IDL.Func([VehicleLocation], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'student' : IDL.Null,
    'driver' : IDL.Null,
    'parent' : IDL.Null,
  });
  const Time = IDL.Int;
  const Alert = IDL.Record({
    'id' : IDL.Text,
    'tripId' : IDL.Opt(IDL.Text),
    'routeId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Time,
    'vehicleId' : IDL.Opt(IDL.Text),
  });
  const PickupDropoffRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'stopId' : IDL.Text,
    'studentId' : IDL.Principal,
    'tripId' : IDL.Text,
    'time' : Time,
    'notes' : IDL.Opt(IDL.Text),
  });
  const Route = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'stops' : IDL.Vec(IDL.Text),
  });
  const TripStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'delayed' : IDL.Null,
    'arrived' : IDL.Null,
    'completed' : IDL.Null,
    'enRoute' : IDL.Null,
  });
  const Trip = IDL.Record({
    'id' : IDL.Text,
    'status' : TripStatus,
    'lastUpdated' : Time,
    'routeId' : IDL.Text,
    'vehicleId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'assignedRoute' : IDL.Opt(IDL.Text),
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'assignedVehicle' : IDL.Opt(IDL.Text),
  });
  const VehicleLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'assignedRoute' : IDL.Opt(IDL.Text),
    'lastUpdated' : Time,
    'longitude' : IDL.Float64,
    'driver' : IDL.Principal,
    'vehicleId' : IDL.Text,
  });
  const TripLifecycleAction = IDL.Record({
    'action' : IDL.Text,
    'routeName' : IDL.Text,
    'routeId' : IDL.Text,
    'timestamp' : Time,
    'driver' : IDL.Principal,
    'vehicleId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignDriverVehicleAndRoute' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlert' : IDL.Func([Alert], [], []),
    'createPickupDropoffRecord' : IDL.Func([PickupDropoffRecord], [], []),
    'createRoute' : IDL.Func([Route], [], []),
    'createTrip' : IDL.Func([Trip], [], []),
    'deactivateRoute' : IDL.Func([IDL.Text], [], []),
    'endTripExplicit' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getActiveRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
    'getActiveTripsForDriver' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Trip)],
        ['query'],
      ),
    'getAlert' : IDL.Func([IDL.Text], [IDL.Opt(Alert)], ['query']),
    'getAlertsForRoute' : IDL.Func([IDL.Text], [IDL.Vec(Alert)], ['query']),
    'getAlertsForVehicle' : IDL.Func([IDL.Text], [IDL.Vec(Alert)], ['query']),
    'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllPickupDropoffRecords' : IDL.Func(
        [],
        [IDL.Vec(PickupDropoffRecord)],
        ['query'],
      ),
    'getAllRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllVehicleLocations' : IDL.Func(
        [],
        [IDL.Vec(VehicleLocation)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDriverTripHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TripLifecycleAction)],
        ['query'],
      ),
    'getPickupDropoffRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PickupDropoffRecord)],
        ['query'],
      ),
    'getPickupDropoffRecordsForStudent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PickupDropoffRecord)],
        ['query'],
      ),
    'getRoute' : IDL.Func([IDL.Text], [IDL.Opt(Route)], ['query']),
    'getTrip' : IDL.Func([IDL.Text], [IDL.Opt(Trip)], ['query']),
    'getTripsForVehicle' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicleLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VehicleLocation)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'startTripExplicit' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePickupDropoffRecord' : IDL.Func([PickupDropoffRecord], [], []),
    'updateRoute' : IDL.Func([Route], [], []),
    'updateTripStatus' : IDL.Func([IDL.Text, TripStatus], [], []),
    'updateVehicleLocation' : IDL.Func([VehicleLocation], [], []),
  });
};

export const init = ({ IDL }) => { return []; };