/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : string,
  'tripId' : [] | [string],
  'routeId' : [] | [string],
  'message' : string,
  'timestamp' : Time,
  'vehicleId' : [] | [string],
}
export interface PickupDropoffRecord {
  'id' : string,
  'status' : string,
  'stopId' : string,
  'studentId' : Principal,
  'tripId' : string,
  'time' : Time,
  'notes' : [] | [string],
}
export interface Route {
  'id' : string,
  'name' : string,
  'isActive' : boolean,
  'stops' : Array<string>,
}
export type Time = bigint;
export interface Trip {
  'id' : string,
  'status' : TripStatus,
  'lastUpdated' : Time,
  'routeId' : string,
  'vehicleId' : string,
}
export interface TripLifecycleAction {
  'action' : string,
  'routeName' : string,
  'routeId' : string,
  'timestamp' : Time,
  'driver' : Principal,
  'vehicleId' : string,
}
export type TripStatus = { 'scheduled' : null } |
  { 'delayed' : null } |
  { 'arrived' : null } |
  { 'completed' : null } |
  { 'enRoute' : null };
export interface UserProfile {
  'assignedRoute' : [] | [string],
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
  'assignedVehicle' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'student' : null } |
  { 'driver' : null } |
  { 'parent' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VehicleLocation {
  'latitude' : number,
  'assignedRoute' : [] | [string],
  'lastUpdated' : Time,
  'longitude' : number,
  'driver' : Principal,
  'vehicleId' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignDriverVehicleAndRoute' : ActorMethod<
    [Principal, [] | [string], [] | [string]],
    undefined
  >,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlert' : ActorMethod<[Alert], undefined>,
  'createPickupDropoffRecord' : ActorMethod<[PickupDropoffRecord], undefined>,
  'createRoute' : ActorMethod<[Route], undefined>,
  'createTrip' : ActorMethod<[Trip], undefined>,
  'deactivateRoute' : ActorMethod<[string], undefined>,
  'endTripExplicit' : ActorMethod<[string, string], undefined>,
  'getActiveRoutes' : ActorMethod<[], Array<Route>>,
  'getActiveTripsForDriver' : ActorMethod<[Principal], Array<Trip>>,
  'getAlert' : ActorMethod<[string], [] | [Alert]>,
  'getAlertsForRoute' : ActorMethod<[string], Array<Alert>>,
  'getAlertsForVehicle' : ActorMethod<[string], Array<Alert>>,
  'getAllAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllPickupDropoffRecords' : ActorMethod<[], Array<PickupDropoffRecord>>,
  'getAllRoutes' : ActorMethod<[], Array<Route>>,
  'getAllTrips' : ActorMethod<[], Array<Trip>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllVehicleLocations' : ActorMethod<[], Array<VehicleLocation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDriverTripHistory' : ActorMethod<[Principal], Array<TripLifecycleAction>>,
  'getPickupDropoffRecord' : ActorMethod<[string], [] | [PickupDropoffRecord]>,
  'getPickupDropoffRecordsForStudent' : ActorMethod<
    [Principal],
    Array<PickupDropoffRecord>
  >,
  'getRoute' : ActorMethod<[string], [] | [Route]>,
  'getTrip' : ActorMethod<[string], [] | [Trip]>,
  'getTripsForVehicle' : ActorMethod<[string], Array<Trip>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicleLocation' : ActorMethod<[string], [] | [VehicleLocation]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'startTripExplicit' : ActorMethod<[string, string], undefined>,
  'updatePickupDropoffRecord' : ActorMethod<[PickupDropoffRecord], undefined>,
  'updateRoute' : ActorMethod<[Route], undefined>,
  'updateTripStatus' : ActorMethod<[string, TripStatus], undefined>,
  'updateVehicleLocation' : ActorMethod<[VehicleLocation], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];