/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Route {
    id: string;
    name: string;
    isActive: boolean;
    stops: Array<string>;
}
export interface Trip {
    id: string;
    status: TripStatus;
    lastUpdated: Time;
    routeId: string;
    vehicleId: string;
}
export type Time = bigint;
export interface PickupDropoffRecord {
    id: string;
    status: string;
    stopId: string;
    studentId: Principal;
    tripId: string;
    time: Time;
    notes?: string;
}
export interface VehicleLocation {
    latitude: number;
    assignedRoute?: string;
    lastUpdated: Time;
    longitude: number;
    driver: Principal;
    vehicleId: string;
}
export interface Alert {
    id: string;
    tripId?: string;
    routeId?: string;
    message: string;
    timestamp: Time;
    vehicleId?: string;
}
export interface TripLifecycleAction {
    action: string;
    routeName: string;
    routeId: string;
    timestamp: Time;
    driver: Principal;
    vehicleId: string;
}
export interface UserProfile {
    assignedRoute?: string;
    principal: Principal;
    name: string;
    role: UserRole;
    assignedVehicle?: string;
}
export enum TripStatus {
    scheduled = "scheduled",
    delayed = "delayed",
    arrived = "arrived",
    completed = "completed",
    enRoute = "enRoute"
}
export enum UserRole {
    admin = "admin",
    student = "student",
    driver = "driver",
    parent = "parent"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignDriverVehicleAndRoute(driver: Principal, vehicleId: string | null, routeId: string | null): Promise<void>;
    assignUserRole(user: Principal, role: UserRole): Promise<void>;
    createAlert(alert: Alert): Promise<void>;
    createPickupDropoffRecord(record: PickupDropoffRecord): Promise<void>;
    createRoute(route: Route): Promise<void>;
    createTrip(trip: Trip): Promise<void>;
    deactivateRoute(routeId: string): Promise<void>;
    endTripExplicit(vehicleId: string, routeId: string): Promise<void>;
    getActiveRoutes(): Promise<Array<Route>>;
    getActiveTripsForDriver(driverId: Principal): Promise<Array<Trip>>;
    getAlert(id: string): Promise<Alert | null>;
    getAlertsForRoute(routeId: string): Promise<Array<Alert>>;
    getAlertsForVehicle(vehicleId: string): Promise<Array<Alert>>;
    getAllAlerts(): Promise<Array<Alert>>;
    getAllPickupDropoffRecords(): Promise<Array<PickupDropoffRecord>>;
    getAllRoutes(): Promise<Array<Route>>;
    getAllTrips(): Promise<Array<Trip>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getAllVehicleLocations(): Promise<Array<VehicleLocation>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDriverTripHistory(driverId: Principal): Promise<Array<TripLifecycleAction>>;
    getPickupDropoffRecord(id: string): Promise<PickupDropoffRecord | null>;
    getPickupDropoffRecordsForStudent(studentId: Principal): Promise<Array<PickupDropoffRecord>>;
    getRoute(id: string): Promise<Route | null>;
    getTrip(id: string): Promise<Trip | null>;
    getTripsForVehicle(vehicleId: string): Promise<Array<Trip>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVehicleLocation(vehicleId: string): Promise<VehicleLocation | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(name: string): Promise<void>;
    startTripExplicit(vehicleId: string, routeId: string): Promise<void>;
    updatePickupDropoffRecord(record: PickupDropoffRecord): Promise<void>;
    updateRoute(route: Route): Promise<void>;
    updateTripStatus(tripId: string, status: TripStatus): Promise<void>;
    updateVehicleLocation(location: VehicleLocation): Promise<void>;
}
import type { Alert as _Alert, PickupDropoffRecord as _PickupDropoffRecord, Route as _Route, Time as _Time, Trip as _Trip, TripStatus as _TripStatus, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, VehicleLocation as _VehicleLocation } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignDriverVehicleAndRoute(arg0: Principal, arg1: string | null, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDriverVehicleAndRoute(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDriverVehicleAndRoute(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAlert(arg0: Alert): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(to_candid_Alert_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(to_candid_Alert_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPickupDropoffRecord(arg0: PickupDropoffRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPickupDropoffRecord(to_candid_PickupDropoffRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPickupDropoffRecord(to_candid_PickupDropoffRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRoute(arg0: Route): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoute(arg0);
            return result;
        }
    }
    async createTrip(arg0: Trip): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(to_candid_Trip_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(to_candid_Trip_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deactivateRoute(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateRoute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateRoute(arg0);
            return result;
        }
    }
    async endTripExplicit(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endTripExplicit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endTripExplicit(arg0, arg1);
            return result;
        }
    }
    async getActiveRoutes(): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveRoutes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveRoutes();
            return result;
        }
    }
    async getActiveTripsForDriver(arg0: Principal): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTripsForDriver(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTripsForDriver(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlert(arg0: string): Promise<Alert | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlert(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlert(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlertsForRoute(arg0: string): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsForRoute(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsForRoute(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlertsForVehicle(arg0: string): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsForVehicle(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsForVehicle(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlerts();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlerts();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPickupDropoffRecords(): Promise<Array<PickupDropoffRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPickupDropoffRecords();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPickupDropoffRecords();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRoutes(): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoutes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoutes();
            return result;
        }
    }
    async getAllTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrips();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrips();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVehicleLocations(): Promise<Array<VehicleLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVehicleLocations();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVehicleLocations();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverTripHistory(arg0: Principal): Promise<Array<TripLifecycleAction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverTripHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverTripHistory(arg0);
            return result;
        }
    }
    async getPickupDropoffRecord(arg0: string): Promise<PickupDropoffRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickupDropoffRecord(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickupDropoffRecord(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPickupDropoffRecordsForStudent(arg0: Principal): Promise<Array<PickupDropoffRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickupDropoffRecordsForStudent(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickupDropoffRecordsForStudent(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoute(arg0: string): Promise<Route | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoute(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoute(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrip(arg0: string): Promise<Trip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripsForVehicle(arg0: string): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripsForVehicle(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripsForVehicle(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicleLocation(arg0: string): Promise<VehicleLocation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicleLocation(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicleLocation(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async startTripExplicit(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTripExplicit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTripExplicit(arg0, arg1);
            return result;
        }
    }
    async updatePickupDropoffRecord(arg0: PickupDropoffRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePickupDropoffRecord(to_candid_PickupDropoffRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePickupDropoffRecord(to_candid_PickupDropoffRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRoute(arg0: Route): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoute(arg0);
            return result;
        }
    }
    async updateTripStatus(arg0: string, arg1: TripStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTripStatus(arg0, to_candid_TripStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTripStatus(arg0, to_candid_TripStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVehicleLocation(arg0: VehicleLocation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicleLocation(to_candid_VehicleLocation_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicleLocation(to_candid_VehicleLocation_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Alert_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_PickupDropoffRecord_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickupDropoffRecord): PickupDropoffRecord {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TripStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripStatus): TripStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleLocation_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleLocation): VehicleLocation {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Alert]): Alert | null {
    return value.length === 0 ? null : from_candid_Alert_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PickupDropoffRecord]): PickupDropoffRecord | null {
    return value.length === 0 ? null : from_candid_PickupDropoffRecord_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Route]): Route | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trip]): Trip | null {
    return value.length === 0 ? null : from_candid_Trip_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VehicleLocation]): VehicleLocation | null {
    return value.length === 0 ? null : from_candid_VehicleLocation_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TripStatus;
    lastUpdated: _Time;
    routeId: string;
    vehicleId: string;
}): {
    id: string;
    status: TripStatus;
    lastUpdated: Time;
    routeId: string;
    vehicleId: string;
} {
    return {
        id: value.id,
        status: from_candid_TripStatus_n17(_uploadFile, _downloadFile, value.status),
        lastUpdated: value.lastUpdated,
        routeId: value.routeId,
        vehicleId: value.vehicleId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    tripId: [] | [string];
    routeId: [] | [string];
    message: string;
    timestamp: _Time;
    vehicleId: [] | [string];
}): {
    id: string;
    tripId?: string;
    routeId?: string;
    message: string;
    timestamp: Time;
    vehicleId?: string;
} {
    return {
        id: value.id,
        tripId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.tripId)),
        routeId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.routeId)),
        message: value.message,
        timestamp: value.timestamp,
        vehicleId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.vehicleId))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    stopId: string;
    studentId: Principal;
    tripId: string;
    time: _Time;
    notes: [] | [string];
}): {
    id: string;
    status: string;
    stopId: string;
    studentId: Principal;
    tripId: string;
    time: Time;
    notes?: string;
} {
    return {
        id: value.id,
        status: value.status,
        stopId: value.stopId,
        studentId: value.studentId,
        tripId: value.tripId,
        time: value.time,
        notes: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedRoute: [] | [string];
    principal: Principal;
    name: string;
    role: _UserRole;
    assignedVehicle: [] | [string];
}): {
    assignedRoute?: string;
    principal: Principal;
    name: string;
    role: UserRole;
    assignedVehicle?: string;
} {
    return {
        assignedRoute: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.assignedRoute)),
        principal: value.principal,
        name: value.name,
        role: from_candid_UserRole_n30(_uploadFile, _downloadFile, value.role),
        assignedVehicle: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.assignedVehicle))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    assignedRoute: [] | [string];
    lastUpdated: _Time;
    longitude: number;
    driver: Principal;
    vehicleId: string;
}): {
    latitude: number;
    assignedRoute?: string;
    lastUpdated: Time;
    longitude: number;
    driver: Principal;
    vehicleId: string;
} {
    return {
        latitude: value.latitude,
        assignedRoute: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.assignedRoute)),
        lastUpdated: value.lastUpdated,
        longitude: value.longitude,
        driver: value.driver,
        vehicleId: value.vehicleId
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    delayed: null;
} | {
    arrived: null;
} | {
    completed: null;
} | {
    enRoute: null;
}): TripStatus {
    return "scheduled" in value ? TripStatus.scheduled : "delayed" in value ? TripStatus.delayed : "arrived" in value ? TripStatus.arrived : "completed" in value ? TripStatus.completed : "enRoute" in value ? TripStatus.enRoute : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    student: null;
} | {
    driver: null;
} | {
    parent: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "student" in value ? UserRole.student : "driver" in value ? UserRole.driver : "parent" in value ? UserRole.parent : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PickupDropoffRecord>): Array<PickupDropoffRecord> {
    return value.map((x)=>from_candid_PickupDropoffRecord_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VehicleLocation>): Array<VehicleLocation> {
    return value.map((x)=>from_candid_VehicleLocation_n33(_uploadFile, _downloadFile, x));
}
function to_candid_Alert_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Alert): _Alert {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_PickupDropoffRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PickupDropoffRecord): _PickupDropoffRecord {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_TripStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): _TripStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Trip_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trip): _Trip {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleLocation_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleLocation): _VehicleLocation {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: TripStatus;
    lastUpdated: Time;
    routeId: string;
    vehicleId: string;
}): {
    id: string;
    status: _TripStatus;
    lastUpdated: _Time;
    routeId: string;
    vehicleId: string;
} {
    return {
        id: value.id,
        status: to_candid_TripStatus_n12(_uploadFile, _downloadFile, value.status),
        lastUpdated: value.lastUpdated,
        routeId: value.routeId,
        vehicleId: value.vehicleId
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    assignedRoute?: string;
    lastUpdated: Time;
    longitude: number;
    driver: Principal;
    vehicleId: string;
}): {
    latitude: number;
    assignedRoute: [] | [string];
    lastUpdated: _Time;
    longitude: number;
    driver: Principal;
    vehicleId: string;
} {
    return {
        latitude: value.latitude,
        assignedRoute: value.assignedRoute ? candid_some(value.assignedRoute) : candid_none(),
        lastUpdated: value.lastUpdated,
        longitude: value.longitude,
        driver: value.driver,
        vehicleId: value.vehicleId
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    tripId?: string;
    routeId?: string;
    message: string;
    timestamp: Time;
    vehicleId?: string;
}): {
    id: string;
    tripId: [] | [string];
    routeId: [] | [string];
    message: string;
    timestamp: _Time;
    vehicleId: [] | [string];
} {
    return {
        id: value.id,
        tripId: value.tripId ? candid_some(value.tripId) : candid_none(),
        routeId: value.routeId ? candid_some(value.routeId) : candid_none(),
        message: value.message,
        timestamp: value.timestamp,
        vehicleId: value.vehicleId ? candid_some(value.vehicleId) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    stopId: string;
    studentId: Principal;
    tripId: string;
    time: Time;
    notes?: string;
}): {
    id: string;
    status: string;
    stopId: string;
    studentId: Principal;
    tripId: string;
    time: _Time;
    notes: [] | [string];
} {
    return {
        id: value.id,
        status: value.status,
        stopId: value.stopId,
        studentId: value.studentId,
        tripId: value.tripId,
        time: value.time,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): {
    scheduled: null;
} | {
    delayed: null;
} | {
    arrived: null;
} | {
    completed: null;
} | {
    enRoute: null;
} {
    return value == TripStatus.scheduled ? {
        scheduled: null
    } : value == TripStatus.delayed ? {
        delayed: null
    } : value == TripStatus.arrived ? {
        arrived: null
    } : value == TripStatus.completed ? {
        completed: null
    } : value == TripStatus.enRoute ? {
        enRoute: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    student: null;
} | {
    driver: null;
} | {
    parent: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.student ? {
        student: null
    } : value == UserRole.driver ? {
        driver: null
    } : value == UserRole.parent ? {
        parent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
